// Code generated by protoc-gen-go.
// source: organise.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	organise.proto

It has these top-level messages:
	Empty
	CombinedRelease
	ReleasePlacement
	Location
	Organisation
	OrganisationList
	LocationMove
	OrganisationMoves
	ReleaseLocation
	DiffRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import godiscogs "github.com/brotherlogic/godiscogs"
import discogsserver "github.com/brotherlogic/discogssyncer/server"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// The means by which the folder is sorted
type Location_Sorting int32

const (
	Location_BY_LABEL_CATNO  Location_Sorting = 0
	Location_BY_DATE_ADDED   Location_Sorting = 1
	Location_BY_RELEASE_DATE Location_Sorting = 2
)

var Location_Sorting_name = map[int32]string{
	0: "BY_LABEL_CATNO",
	1: "BY_DATE_ADDED",
	2: "BY_RELEASE_DATE",
}
var Location_Sorting_value = map[string]int32{
	"BY_LABEL_CATNO":  0,
	"BY_DATE_ADDED":   1,
	"BY_RELEASE_DATE": 2,
}

func (x Location_Sorting) String() string {
	return proto1.EnumName(Location_Sorting_name, int32(x))
}
func (Location_Sorting) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CombinedRelease struct {
	Release  *godiscogs.Release             `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	Metadata *discogsserver.ReleaseMetadata `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
}

func (m *CombinedRelease) Reset()                    { *m = CombinedRelease{} }
func (m *CombinedRelease) String() string            { return proto1.CompactTextString(m) }
func (*CombinedRelease) ProtoMessage()               {}
func (*CombinedRelease) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CombinedRelease) GetRelease() *godiscogs.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *CombinedRelease) GetMetadata() *discogsserver.ReleaseMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ReleasePlacement struct {
	// The id of the release
	ReleaseId int32 `protobuf:"varint,1,opt,name=release_id,json=releaseId" json:"release_id,omitempty"`
	// The index in the folder
	Index int32 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	// The slot in the folder
	Slot int32 `protobuf:"varint,3,opt,name=slot" json:"slot,omitempty"`
	// The prior release
	BeforeReleaseId int32 `protobuf:"varint,4,opt,name=before_release_id,json=beforeReleaseId" json:"before_release_id,omitempty"`
	// The following release
	AfterReleaseId int32 `protobuf:"varint,5,opt,name=after_release_id,json=afterReleaseId" json:"after_release_id,omitempty"`
	// The name of the folder
	Folder string `protobuf:"bytes,6,opt,name=folder" json:"folder,omitempty"`
}

func (m *ReleasePlacement) Reset()                    { *m = ReleasePlacement{} }
func (m *ReleasePlacement) String() string            { return proto1.CompactTextString(m) }
func (*ReleasePlacement) ProtoMessage()               {}
func (*ReleasePlacement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Location struct {
	// The name of the location
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The number of units within the location
	Units int32 `protobuf:"varint,2,opt,name=units" json:"units,omitempty"`
	// The folder ids that are stored in this location
	FolderIds []int32 `protobuf:"varint,3,rep,name=folder_ids,json=folderIds" json:"folder_ids,omitempty"`
	// The placement of releases in the folder
	ReleasesLocation []*ReleasePlacement `protobuf:"bytes,4,rep,name=releases_location,json=releasesLocation" json:"releases_location,omitempty"`
	Sort             Location_Sorting    `protobuf:"varint,5,opt,name=sort,enum=proto.Location_Sorting" json:"sort,omitempty"`
	// The timestamp of this given location / arrangement
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto1.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Location) GetReleasesLocation() []*ReleasePlacement {
	if m != nil {
		return m.ReleasesLocation
	}
	return nil
}

type Organisation struct {
	// Timestamp this organisation was made
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	// The locations in this sorting
	Locations []*Location `protobuf:"bytes,2,rep,name=locations" json:"locations,omitempty"`
}

func (m *Organisation) Reset()                    { *m = Organisation{} }
func (m *Organisation) String() string            { return proto1.CompactTextString(m) }
func (*Organisation) ProtoMessage()               {}
func (*Organisation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Organisation) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

type OrganisationList struct {
	Organisations []*Organisation `protobuf:"bytes,1,rep,name=organisations" json:"organisations,omitempty"`
}

func (m *OrganisationList) Reset()                    { *m = OrganisationList{} }
func (m *OrganisationList) String() string            { return proto1.CompactTextString(m) }
func (*OrganisationList) ProtoMessage()               {}
func (*OrganisationList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *OrganisationList) GetOrganisations() []*Organisation {
	if m != nil {
		return m.Organisations
	}
	return nil
}

type LocationMove struct {
	Old *ReleasePlacement `protobuf:"bytes,1,opt,name=old" json:"old,omitempty"`
	New *ReleasePlacement `protobuf:"bytes,2,opt,name=new" json:"new,omitempty"`
}

func (m *LocationMove) Reset()                    { *m = LocationMove{} }
func (m *LocationMove) String() string            { return proto1.CompactTextString(m) }
func (*LocationMove) ProtoMessage()               {}
func (*LocationMove) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *LocationMove) GetOld() *ReleasePlacement {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *LocationMove) GetNew() *ReleasePlacement {
	if m != nil {
		return m.New
	}
	return nil
}

type OrganisationMoves struct {
	StartTimestamp int64           `protobuf:"varint,1,opt,name=start_timestamp,json=startTimestamp" json:"start_timestamp,omitempty"`
	EndTimestamp   int64           `protobuf:"varint,2,opt,name=end_timestamp,json=endTimestamp" json:"end_timestamp,omitempty"`
	Moves          []*LocationMove `protobuf:"bytes,3,rep,name=moves" json:"moves,omitempty"`
}

func (m *OrganisationMoves) Reset()                    { *m = OrganisationMoves{} }
func (m *OrganisationMoves) String() string            { return proto1.CompactTextString(m) }
func (*OrganisationMoves) ProtoMessage()               {}
func (*OrganisationMoves) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *OrganisationMoves) GetMoves() []*LocationMove {
	if m != nil {
		return m.Moves
	}
	return nil
}

type ReleaseLocation struct {
	Location *Location          `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Slot     int32              `protobuf:"varint,2,opt,name=slot" json:"slot,omitempty"`
	Before   *godiscogs.Release `protobuf:"bytes,3,opt,name=before" json:"before,omitempty"`
	After    *godiscogs.Release `protobuf:"bytes,4,opt,name=after" json:"after,omitempty"`
}

func (m *ReleaseLocation) Reset()                    { *m = ReleaseLocation{} }
func (m *ReleaseLocation) String() string            { return proto1.CompactTextString(m) }
func (*ReleaseLocation) ProtoMessage()               {}
func (*ReleaseLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ReleaseLocation) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *ReleaseLocation) GetBefore() *godiscogs.Release {
	if m != nil {
		return m.Before
	}
	return nil
}

func (m *ReleaseLocation) GetAfter() *godiscogs.Release {
	if m != nil {
		return m.After
	}
	return nil
}

type DiffRequest struct {
	StartTimestamp int64  `protobuf:"varint,1,opt,name=start_timestamp,json=startTimestamp" json:"start_timestamp,omitempty"`
	EndTimestamp   int64  `protobuf:"varint,2,opt,name=end_timestamp,json=endTimestamp" json:"end_timestamp,omitempty"`
	LocationName   string `protobuf:"bytes,3,opt,name=location_name,json=locationName" json:"location_name,omitempty"`
	Slot           int32  `protobuf:"varint,4,opt,name=slot" json:"slot,omitempty"`
}

func (m *DiffRequest) Reset()                    { *m = DiffRequest{} }
func (m *DiffRequest) String() string            { return proto1.CompactTextString(m) }
func (*DiffRequest) ProtoMessage()               {}
func (*DiffRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*CombinedRelease)(nil), "proto.CombinedRelease")
	proto1.RegisterType((*ReleasePlacement)(nil), "proto.ReleasePlacement")
	proto1.RegisterType((*Location)(nil), "proto.Location")
	proto1.RegisterType((*Organisation)(nil), "proto.Organisation")
	proto1.RegisterType((*OrganisationList)(nil), "proto.OrganisationList")
	proto1.RegisterType((*LocationMove)(nil), "proto.LocationMove")
	proto1.RegisterType((*OrganisationMoves)(nil), "proto.OrganisationMoves")
	proto1.RegisterType((*ReleaseLocation)(nil), "proto.ReleaseLocation")
	proto1.RegisterType((*DiffRequest)(nil), "proto.DiffRequest")
	proto1.RegisterEnum("proto.Location_Sorting", Location_Sorting_name, Location_Sorting_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for OrganiserService service

type OrganiserServiceClient interface {
	Organise(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrganisationMoves, error)
	Locate(ctx context.Context, in *godiscogs.Release, opts ...grpc.CallOption) (*ReleaseLocation, error)
	AddLocation(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Location, error)
	GetLocation(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Location, error)
	GetOrganisations(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrganisationList, error)
	GetOrganisation(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Organisation, error)
	UpdateLocation(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Location, error)
	Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*OrganisationMoves, error)
}

type organiserServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrganiserServiceClient(cc *grpc.ClientConn) OrganiserServiceClient {
	return &organiserServiceClient{cc}
}

func (c *organiserServiceClient) Organise(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrganisationMoves, error) {
	out := new(OrganisationMoves)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/Organise", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) Locate(ctx context.Context, in *godiscogs.Release, opts ...grpc.CallOption) (*ReleaseLocation, error) {
	out := new(ReleaseLocation)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/Locate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) AddLocation(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Location, error) {
	out := new(Location)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/AddLocation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) GetLocation(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Location, error) {
	out := new(Location)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/GetLocation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) GetOrganisations(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrganisationList, error) {
	out := new(OrganisationList)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/GetOrganisations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) GetOrganisation(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Organisation, error) {
	out := new(Organisation)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/GetOrganisation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) UpdateLocation(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Location, error) {
	out := new(Location)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/UpdateLocation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*OrganisationMoves, error) {
	out := new(OrganisationMoves)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/Diff", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrganiserService service

type OrganiserServiceServer interface {
	Organise(context.Context, *Empty) (*OrganisationMoves, error)
	Locate(context.Context, *godiscogs.Release) (*ReleaseLocation, error)
	AddLocation(context.Context, *Location) (*Location, error)
	GetLocation(context.Context, *Location) (*Location, error)
	GetOrganisations(context.Context, *Empty) (*OrganisationList, error)
	GetOrganisation(context.Context, *Empty) (*Organisation, error)
	UpdateLocation(context.Context, *Location) (*Location, error)
	Diff(context.Context, *DiffRequest) (*OrganisationMoves, error)
}

func RegisterOrganiserServiceServer(s *grpc.Server, srv OrganiserServiceServer) {
	s.RegisterService(&_OrganiserService_serviceDesc, srv)
}

func _OrganiserService_Organise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).Organise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/Organise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).Organise(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_Locate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(godiscogs.Release)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).Locate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/Locate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).Locate(ctx, req.(*godiscogs.Release))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_AddLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Location)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).AddLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/AddLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).AddLocation(ctx, req.(*Location))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_GetLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Location)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).GetLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/GetLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).GetLocation(ctx, req.(*Location))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_GetOrganisations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).GetOrganisations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/GetOrganisations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).GetOrganisations(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_GetOrganisation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).GetOrganisation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/GetOrganisation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).GetOrganisation(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Location)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/UpdateLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).UpdateLocation(ctx, req.(*Location))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_Diff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).Diff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/Diff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).Diff(ctx, req.(*DiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrganiserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OrganiserService",
	HandlerType: (*OrganiserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Organise",
			Handler:    _OrganiserService_Organise_Handler,
		},
		{
			MethodName: "Locate",
			Handler:    _OrganiserService_Locate_Handler,
		},
		{
			MethodName: "AddLocation",
			Handler:    _OrganiserService_AddLocation_Handler,
		},
		{
			MethodName: "GetLocation",
			Handler:    _OrganiserService_GetLocation_Handler,
		},
		{
			MethodName: "GetOrganisations",
			Handler:    _OrganiserService_GetOrganisations_Handler,
		},
		{
			MethodName: "GetOrganisation",
			Handler:    _OrganiserService_GetOrganisation_Handler,
		},
		{
			MethodName: "UpdateLocation",
			Handler:    _OrganiserService_UpdateLocation_Handler,
		},
		{
			MethodName: "Diff",
			Handler:    _OrganiserService_Diff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("organise.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 803 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x4e, 0xeb, 0x46,
	0x10, 0xc6, 0x49, 0x1c, 0x92, 0x21, 0x24, 0xce, 0x52, 0x41, 0x14, 0xb5, 0x55, 0xe5, 0x5e, 0x14,
	0xfa, 0x13, 0x04, 0x45, 0x48, 0xb4, 0x57, 0x81, 0x58, 0x15, 0x52, 0x80, 0x6a, 0xa1, 0x17, 0x55,
	0x2f, 0x2c, 0x27, 0xde, 0x04, 0x4b, 0xb1, 0x37, 0xf5, 0x2e, 0xb4, 0xa8, 0xaf, 0xd0, 0xcb, 0xf3,
	0x10, 0x47, 0x3a, 0x4f, 0xc2, 0x5b, 0x9d, 0xf5, 0xee, 0xfa, 0x27, 0x26, 0x1c, 0x09, 0xe9, 0x5c,
	0xc5, 0x9e, 0xf9, 0xe6, 0xe7, 0x9b, 0x99, 0xcf, 0x81, 0x36, 0x8d, 0xe7, 0x5e, 0x14, 0x30, 0x32,
	0x58, 0xc6, 0x94, 0x53, 0x64, 0xca, 0x9f, 0xfe, 0xd1, 0x3c, 0xe0, 0xf7, 0x0f, 0x93, 0xc1, 0x94,
	0x86, 0x87, 0x13, 0x61, 0xb9, 0x27, 0xf1, 0x82, 0xce, 0x83, 0xe9, 0xe1, 0x9c, 0xfa, 0x01, 0x9b,
	0xd2, 0x39, 0xcb, 0x9f, 0x54, 0x64, 0xff, 0xec, 0xb5, 0x10, 0x0d, 0x63, 0x4f, 0xd1, 0x94, 0xc4,
	0x87, 0x8c, 0xc4, 0x8f, 0xd9, 0x8f, 0x0a, 0xb5, 0x37, 0xc1, 0x74, 0xc2, 0x25, 0x7f, 0xb2, 0xff,
	0x83, 0xce, 0x05, 0x0d, 0x27, 0x41, 0x44, 0x7c, 0x4c, 0x16, 0xc4, 0x63, 0x04, 0xfd, 0x08, 0x9b,
	0xb1, 0x7a, 0xec, 0x19, 0xdf, 0x18, 0xfb, 0x5b, 0xc7, 0x68, 0x90, 0x57, 0xd6, 0x20, 0x9c, 0x42,
	0xd0, 0x2f, 0xd0, 0x08, 0x09, 0xf7, 0x7c, 0x8f, 0x7b, 0xbd, 0x8a, 0x84, 0x7f, 0x3d, 0x48, 0xeb,
	0xab, 0x8a, 0x3a, 0xe4, 0x4a, 0xa3, 0x70, 0x86, 0xb7, 0x9f, 0x0d, 0xb0, 0xb4, 0xf7, 0xf7, 0x85,
	0x37, 0x25, 0x21, 0x89, 0x38, 0xfa, 0x0a, 0x40, 0xe7, 0x76, 0x03, 0x5f, 0x76, 0x60, 0xe2, 0xa6,
	0xb6, 0x5c, 0xfa, 0xe8, 0x0b, 0x30, 0x83, 0xc8, 0x27, 0xff, 0xca, 0x62, 0x26, 0x56, 0x2f, 0x08,
	0x41, 0x8d, 0x2d, 0x28, 0xef, 0x55, 0xa5, 0x51, 0x3e, 0xa3, 0xef, 0xa1, 0x3b, 0x21, 0x33, 0x1a,
	0x13, 0xb7, 0x90, 0xaf, 0x26, 0x01, 0x1d, 0xe5, 0xc0, 0x59, 0xd6, 0x7d, 0xb0, 0xbc, 0x19, 0x27,
	0x71, 0x11, 0x6a, 0x4a, 0x68, 0x5b, 0xda, 0x73, 0xe4, 0x2e, 0xd4, 0x67, 0x74, 0xe1, 0x93, 0xb8,
	0x57, 0x17, 0xfe, 0x26, 0xd6, 0x6f, 0xf6, 0x87, 0x0a, 0x34, 0xc6, 0x74, 0xea, 0xf1, 0x80, 0x46,
	0x49, 0x3b, 0x91, 0x17, 0xaa, 0xf9, 0x35, 0xb1, 0x7c, 0x4e, 0x1a, 0x7f, 0x88, 0x02, 0xce, 0xd2,
	0xc6, 0xe5, 0x4b, 0xc2, 0x56, 0x25, 0x10, 0x15, 0x99, 0x68, 0xbf, 0x9a, 0xb0, 0x55, 0x96, 0x4b,
	0x9f, 0xa1, 0x11, 0x74, 0x75, 0x47, 0xcc, 0x5d, 0xe8, 0xec, 0x82, 0x43, 0x55, 0x8c, 0x79, 0x4f,
	0xad, 0x72, 0x50, 0x1e, 0x20, 0xb6, 0xd2, 0x88, 0xac, 0x9d, 0x1f, 0xc4, 0x74, 0x68, 0xcc, 0x25,
	0xa3, 0x76, 0x16, 0x98, 0xba, 0x07, 0xb7, 0xc2, 0x17, 0x44, 0x73, 0x2c, 0x41, 0xe8, 0x4b, 0x68,
	0xf2, 0x20, 0x24, 0x8c, 0x7b, 0xe1, 0x52, 0x72, 0xac, 0xe2, 0xdc, 0x60, 0x3b, 0xb0, 0xa9, 0xe1,
	0x82, 0x64, 0xfb, 0xfc, 0x4f, 0x77, 0x3c, 0x3c, 0x77, 0xc6, 0xee, 0xc5, 0xf0, 0xee, 0xfa, 0xc6,
	0xda, 0x40, 0x5d, 0xd8, 0x16, 0xb6, 0xd1, 0xf0, 0xce, 0x71, 0x87, 0xa3, 0x91, 0x33, 0xb2, 0x0c,
	0xb4, 0x03, 0x1d, 0x61, 0xc2, 0xce, 0xd8, 0x19, 0xde, 0x3a, 0xd2, 0x65, 0x55, 0xec, 0xbf, 0xa0,
	0x75, 0xa3, 0x64, 0xa0, 0x3a, 0x5c, 0x29, 0x6a, 0x94, 0x8a, 0xa2, 0x9f, 0xa0, 0x99, 0x92, 0x4f,
	0xc6, 0x97, 0xb0, 0xef, 0x94, 0x48, 0xe0, 0x1c, 0x61, 0x5f, 0x81, 0x55, 0x4c, 0x3e, 0x0e, 0x18,
	0x47, 0x67, 0xb0, 0x4d, 0x0b, 0x36, 0x26, 0x8a, 0x24, 0x69, 0x76, 0x74, 0x9a, 0x22, 0x1e, 0xaf,
	0x22, 0x6d, 0x1f, 0x5a, 0x69, 0x95, 0x2b, 0xfa, 0x48, 0xd0, 0x01, 0x54, 0xc5, 0x7e, 0xb4, 0x36,
	0x5e, 0xdd, 0x42, 0x82, 0x49, 0xa0, 0x11, 0xf9, 0x47, 0xeb, 0xe2, 0x75, 0xa8, 0xc0, 0xd8, 0xff,
	0x1b, 0xd0, 0x2d, 0x76, 0x91, 0x94, 0x62, 0xe8, 0x3b, 0xe8, 0x88, 0x11, 0xc4, 0xdc, 0x2d, 0x4f,
	0xa7, 0x2d, 0xcd, 0x77, 0xd9, 0x88, 0xbe, 0x85, 0x6d, 0x12, 0xf9, 0x05, 0x58, 0x45, 0xc2, 0x5a,
	0xc2, 0x98, 0x83, 0x0e, 0xc0, 0x0c, 0x93, 0xb4, 0xf2, 0xce, 0x72, 0xf2, 0x45, 0x76, 0x58, 0x21,
	0xec, 0xf7, 0x06, 0x74, 0x74, 0xa3, 0x85, 0x33, 0x6a, 0x64, 0x37, 0xa8, 0xd8, 0xbf, 0xd8, 0x42,
	0x06, 0xc8, 0x14, 0x59, 0x59, 0x51, 0x64, 0x5d, 0x09, 0x4f, 0xea, 0x74, 0xfd, 0x87, 0x45, 0x23,
	0x84, 0x22, 0x4d, 0xa9, 0x3c, 0xa9, 0xd8, 0xf5, 0x50, 0x05, 0xb0, 0xdf, 0x19, 0xb0, 0x35, 0x0a,
	0x66, 0x33, 0x4c, 0xfe, 0x7e, 0x10, 0x44, 0x3f, 0xf3, 0xcc, 0x04, 0x28, 0xe5, 0xe4, 0x4a, 0x4d,
	0x57, 0xa5, 0xa6, 0x5b, 0xa9, 0xf1, 0x3a, 0xd1, 0x76, 0x4a, 0xb6, 0x96, 0x93, 0x3d, 0x7e, 0xae,
	0x66, 0x67, 0x48, 0xe2, 0x5b, 0xf1, 0x29, 0x0c, 0xa6, 0x04, 0x9d, 0x40, 0x23, 0xb5, 0xa1, 0x96,
	0x1e, 0x9e, 0xfc, 0x10, 0xf7, 0x7b, 0x6b, 0x2e, 0x51, 0xde, 0x80, 0xbd, 0x81, 0x4e, 0xa1, 0x2e,
	0x27, 0x2c, 0x0a, 0xbd, 0x1c, 0x43, 0x7f, 0x77, 0xf5, 0xae, 0xd2, 0x5d, 0x88, 0xb8, 0x23, 0xd8,
	0x1a, 0xfa, 0x7e, 0xb6, 0xbf, 0xf2, 0xb6, 0xfa, 0x65, 0x83, 0x0a, 0xf9, 0x8d, 0xf0, 0x37, 0x85,
	0xfc, 0x0a, 0x96, 0x08, 0x29, 0xf6, 0xcd, 0x4a, 0xdc, 0xf6, 0xd6, 0x70, 0x4b, 0x54, 0x29, 0xa9,
	0x75, 0x4a, 0xc1, 0xa5, 0xd8, 0x75, 0x0a, 0x15, 0x71, 0x27, 0xd0, 0xfe, 0x63, 0x29, 0xfe, 0x44,
	0xc8, 0x9b, 0x5a, 0x3d, 0x85, 0x5a, 0x72, 0x29, 0x62, 0x8c, 0xca, 0x55, 0x38, 0x9b, 0x4f, 0x2d,
	0x60, 0x52, 0x97, 0xae, 0x9f, 0x3f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x10, 0xc4, 0x29, 0x49, 0xbc,
	0x07, 0x00, 0x00,
}
