// Code generated by protoc-gen-go. DO NOT EDIT.
// source: organise.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	organise.proto

It has these top-level messages:
	Empty
	LabelExtractor
	ReleasePlacement
	Quota
	Location
	Organisation
	AddLocationRequest
	AddLocationResponse
	GetOrganisationRequest
	GetOrganisationResponse
	LocateRequest
	LocateResponse
	QuotaRequest
	QuotaResponse
	UpdateLocationRequest
	UpdateLocationResponse
	AddExtractorRequest
	AddExtractorResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// The means by which the folder is sorted
type Location_Sorting int32

const (
	Location_BY_LABEL_CATNO  Location_Sorting = 0
	Location_BY_DATE_ADDED   Location_Sorting = 1
	Location_BY_RELEASE_DATE Location_Sorting = 2
)

var Location_Sorting_name = map[int32]string{
	0: "BY_LABEL_CATNO",
	1: "BY_DATE_ADDED",
	2: "BY_RELEASE_DATE",
}
var Location_Sorting_value = map[string]int32{
	"BY_LABEL_CATNO":  0,
	"BY_DATE_ADDED":   1,
	"BY_RELEASE_DATE": 2,
}

func (x Location_Sorting) String() string {
	return proto1.EnumName(Location_Sorting_name, int32(x))
}
func (Location_Sorting) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LabelExtractor struct {
	// The id of the label
	LabelId int32 `protobuf:"varint,1,opt,name=label_id,json=labelId" json:"label_id,omitempty"`
	// The extractor
	Extractor string `protobuf:"bytes,2,opt,name=extractor" json:"extractor,omitempty"`
}

func (m *LabelExtractor) Reset()                    { *m = LabelExtractor{} }
func (m *LabelExtractor) String() string            { return proto1.CompactTextString(m) }
func (*LabelExtractor) ProtoMessage()               {}
func (*LabelExtractor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LabelExtractor) GetLabelId() int32 {
	if m != nil {
		return m.LabelId
	}
	return 0
}

func (m *LabelExtractor) GetExtractor() string {
	if m != nil {
		return m.Extractor
	}
	return ""
}

type ReleasePlacement struct {
	// The id of the release
	InstanceId int32 `protobuf:"varint,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	// The index in the folder
	Index int32 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	// The slot in the folder
	Slot int32 `protobuf:"varint,3,opt,name=slot" json:"slot,omitempty"`
}

func (m *ReleasePlacement) Reset()                    { *m = ReleasePlacement{} }
func (m *ReleasePlacement) String() string            { return proto1.CompactTextString(m) }
func (*ReleasePlacement) ProtoMessage()               {}
func (*ReleasePlacement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReleasePlacement) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *ReleasePlacement) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ReleasePlacement) GetSlot() int32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

type Quota struct {
	// The number of allowed units
	NumOfSlots int32 `protobuf:"varint,1,opt,name=num_of_slots,json=numOfSlots" json:"num_of_slots,omitempty"`
	// The total width of the set
	TotalWidth int32 `protobuf:"varint,2,opt,name=total_width,json=totalWidth" json:"total_width,omitempty"`
}

func (m *Quota) Reset()                    { *m = Quota{} }
func (m *Quota) String() string            { return proto1.CompactTextString(m) }
func (*Quota) ProtoMessage()               {}
func (*Quota) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Quota) GetNumOfSlots() int32 {
	if m != nil {
		return m.NumOfSlots
	}
	return 0
}

func (m *Quota) GetTotalWidth() int32 {
	if m != nil {
		return m.TotalWidth
	}
	return 0
}

type Location struct {
	// The name of the location
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The number of units within the location
	Slots int32 `protobuf:"varint,2,opt,name=slots" json:"slots,omitempty"`
	// The folder ids that are stored in this location
	FolderIds []int32 `protobuf:"varint,3,rep,packed,name=folder_ids,json=folderIds" json:"folder_ids,omitempty"`
	// The placement of releases in the folder
	ReleasesLocation []*ReleasePlacement `protobuf:"bytes,4,rep,name=releases_location,json=releasesLocation" json:"releases_location,omitempty"`
	Sort             Location_Sorting    `protobuf:"varint,5,opt,name=sort,enum=proto.Location_Sorting" json:"sort,omitempty"`
	// The timestamp of this given location / arrangement
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp" json:"timestamp,omitempty"`
	// The allowed quota for this location, if any
	Quota *Quota `protobuf:"bytes,7,opt,name=quota" json:"quota,omitempty"`
	// The type of format we expect in this location
	ExpectedFormat string `protobuf:"bytes,8,opt,name=expected_format,json=expectedFormat" json:"expected_format,omitempty"`
	// The type of label we don't expect in this location
	UnexpectedLabel string `protobuf:"bytes,9,opt,name=unexpected_label,json=unexpectedLabel" json:"unexpected_label,omitempty"`
	// Don't send an alert when there are quota problems
	NoAlert bool `protobuf:"varint,10,opt,name=no_alert,json=noAlert" json:"no_alert,omitempty"`
	// Folder to move to when this is over quota
	SpillFolder int32 `protobuf:"varint,11,opt,name=spill_folder,json=spillFolder" json:"spill_folder,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto1.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Location) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Location) GetSlots() int32 {
	if m != nil {
		return m.Slots
	}
	return 0
}

func (m *Location) GetFolderIds() []int32 {
	if m != nil {
		return m.FolderIds
	}
	return nil
}

func (m *Location) GetReleasesLocation() []*ReleasePlacement {
	if m != nil {
		return m.ReleasesLocation
	}
	return nil
}

func (m *Location) GetSort() Location_Sorting {
	if m != nil {
		return m.Sort
	}
	return Location_BY_LABEL_CATNO
}

func (m *Location) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Location) GetQuota() *Quota {
	if m != nil {
		return m.Quota
	}
	return nil
}

func (m *Location) GetExpectedFormat() string {
	if m != nil {
		return m.ExpectedFormat
	}
	return ""
}

func (m *Location) GetUnexpectedLabel() string {
	if m != nil {
		return m.UnexpectedLabel
	}
	return ""
}

func (m *Location) GetNoAlert() bool {
	if m != nil {
		return m.NoAlert
	}
	return false
}

func (m *Location) GetSpillFolder() int32 {
	if m != nil {
		return m.SpillFolder
	}
	return 0
}

type Organisation struct {
	// Timestamp this organisation was made
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	// The locations in this sorting
	Locations []*Location `protobuf:"bytes,2,rep,name=locations" json:"locations,omitempty"`
	// The extractors used for sorting
	Extractors []*LabelExtractor `protobuf:"bytes,3,rep,name=extractors" json:"extractors,omitempty"`
}

func (m *Organisation) Reset()                    { *m = Organisation{} }
func (m *Organisation) String() string            { return proto1.CompactTextString(m) }
func (*Organisation) ProtoMessage()               {}
func (*Organisation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Organisation) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Organisation) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *Organisation) GetExtractors() []*LabelExtractor {
	if m != nil {
		return m.Extractors
	}
	return nil
}

type AddLocationRequest struct {
	Add *Location `protobuf:"bytes,1,opt,name=add" json:"add,omitempty"`
}

func (m *AddLocationRequest) Reset()                    { *m = AddLocationRequest{} }
func (m *AddLocationRequest) String() string            { return proto1.CompactTextString(m) }
func (*AddLocationRequest) ProtoMessage()               {}
func (*AddLocationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AddLocationRequest) GetAdd() *Location {
	if m != nil {
		return m.Add
	}
	return nil
}

type AddLocationResponse struct {
	Now *Organisation `protobuf:"bytes,1,opt,name=now" json:"now,omitempty"`
}

func (m *AddLocationResponse) Reset()                    { *m = AddLocationResponse{} }
func (m *AddLocationResponse) String() string            { return proto1.CompactTextString(m) }
func (*AddLocationResponse) ProtoMessage()               {}
func (*AddLocationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AddLocationResponse) GetNow() *Organisation {
	if m != nil {
		return m.Now
	}
	return nil
}

type GetOrganisationRequest struct {
	Locations []*Location `protobuf:"bytes,1,rep,name=locations" json:"locations,omitempty"`
	// Force a reorg on returned locations
	ForceReorg bool `protobuf:"varint,2,opt,name=force_reorg,json=forceReorg" json:"force_reorg,omitempty"`
}

func (m *GetOrganisationRequest) Reset()                    { *m = GetOrganisationRequest{} }
func (m *GetOrganisationRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetOrganisationRequest) ProtoMessage()               {}
func (*GetOrganisationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetOrganisationRequest) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *GetOrganisationRequest) GetForceReorg() bool {
	if m != nil {
		return m.ForceReorg
	}
	return false
}

type GetOrganisationResponse struct {
	Locations       []*Location `protobuf:"bytes,1,rep,name=locations" json:"locations,omitempty"`
	NumberProcessed int32       `protobuf:"varint,2,opt,name=number_processed,json=numberProcessed" json:"number_processed,omitempty"`
}

func (m *GetOrganisationResponse) Reset()                    { *m = GetOrganisationResponse{} }
func (m *GetOrganisationResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetOrganisationResponse) ProtoMessage()               {}
func (*GetOrganisationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetOrganisationResponse) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *GetOrganisationResponse) GetNumberProcessed() int32 {
	if m != nil {
		return m.NumberProcessed
	}
	return 0
}

type LocateRequest struct {
	InstanceId int32 `protobuf:"varint,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
}

func (m *LocateRequest) Reset()                    { *m = LocateRequest{} }
func (m *LocateRequest) String() string            { return proto1.CompactTextString(m) }
func (*LocateRequest) ProtoMessage()               {}
func (*LocateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *LocateRequest) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

type LocateResponse struct {
	FoundLocation *Location `protobuf:"bytes,2,opt,name=found_location,json=foundLocation" json:"found_location,omitempty"`
}

func (m *LocateResponse) Reset()                    { *m = LocateResponse{} }
func (m *LocateResponse) String() string            { return proto1.CompactTextString(m) }
func (*LocateResponse) ProtoMessage()               {}
func (*LocateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *LocateResponse) GetFoundLocation() *Location {
	if m != nil {
		return m.FoundLocation
	}
	return nil
}

type QuotaRequest struct {
	FolderId       int32  `protobuf:"varint,1,opt,name=folder_id,json=folderId" json:"folder_id,omitempty"`
	IncludeRecords bool   `protobuf:"varint,2,opt,name=include_records,json=includeRecords" json:"include_records,omitempty"`
	Name           string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *QuotaRequest) Reset()                    { *m = QuotaRequest{} }
func (m *QuotaRequest) String() string            { return proto1.CompactTextString(m) }
func (*QuotaRequest) ProtoMessage()               {}
func (*QuotaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *QuotaRequest) GetFolderId() int32 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

func (m *QuotaRequest) GetIncludeRecords() bool {
	if m != nil {
		return m.IncludeRecords
	}
	return false
}

func (m *QuotaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type QuotaResponse struct {
	OverQuota    bool    `protobuf:"varint,1,opt,name=over_quota,json=overQuota" json:"over_quota,omitempty"`
	SpillFolder  int32   `protobuf:"varint,2,opt,name=spill_folder,json=spillFolder" json:"spill_folder,omitempty"`
	LocationName string  `protobuf:"bytes,3,opt,name=location_name,json=locationName" json:"location_name,omitempty"`
	InstanceId   []int32 `protobuf:"varint,4,rep,packed,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
}

func (m *QuotaResponse) Reset()                    { *m = QuotaResponse{} }
func (m *QuotaResponse) String() string            { return proto1.CompactTextString(m) }
func (*QuotaResponse) ProtoMessage()               {}
func (*QuotaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *QuotaResponse) GetOverQuota() bool {
	if m != nil {
		return m.OverQuota
	}
	return false
}

func (m *QuotaResponse) GetSpillFolder() int32 {
	if m != nil {
		return m.SpillFolder
	}
	return 0
}

func (m *QuotaResponse) GetLocationName() string {
	if m != nil {
		return m.LocationName
	}
	return ""
}

func (m *QuotaResponse) GetInstanceId() []int32 {
	if m != nil {
		return m.InstanceId
	}
	return nil
}

type UpdateLocationRequest struct {
	Location string    `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Update   *Location `protobuf:"bytes,2,opt,name=update" json:"update,omitempty"`
}

func (m *UpdateLocationRequest) Reset()                    { *m = UpdateLocationRequest{} }
func (m *UpdateLocationRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateLocationRequest) ProtoMessage()               {}
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *UpdateLocationRequest) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *UpdateLocationRequest) GetUpdate() *Location {
	if m != nil {
		return m.Update
	}
	return nil
}

type UpdateLocationResponse struct {
}

func (m *UpdateLocationResponse) Reset()                    { *m = UpdateLocationResponse{} }
func (m *UpdateLocationResponse) String() string            { return proto1.CompactTextString(m) }
func (*UpdateLocationResponse) ProtoMessage()               {}
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type AddExtractorRequest struct {
	Extractor *LabelExtractor `protobuf:"bytes,1,opt,name=extractor" json:"extractor,omitempty"`
}

func (m *AddExtractorRequest) Reset()                    { *m = AddExtractorRequest{} }
func (m *AddExtractorRequest) String() string            { return proto1.CompactTextString(m) }
func (*AddExtractorRequest) ProtoMessage()               {}
func (*AddExtractorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *AddExtractorRequest) GetExtractor() *LabelExtractor {
	if m != nil {
		return m.Extractor
	}
	return nil
}

type AddExtractorResponse struct {
}

func (m *AddExtractorResponse) Reset()                    { *m = AddExtractorResponse{} }
func (m *AddExtractorResponse) String() string            { return proto1.CompactTextString(m) }
func (*AddExtractorResponse) ProtoMessage()               {}
func (*AddExtractorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func init() {
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*LabelExtractor)(nil), "proto.LabelExtractor")
	proto1.RegisterType((*ReleasePlacement)(nil), "proto.ReleasePlacement")
	proto1.RegisterType((*Quota)(nil), "proto.Quota")
	proto1.RegisterType((*Location)(nil), "proto.Location")
	proto1.RegisterType((*Organisation)(nil), "proto.Organisation")
	proto1.RegisterType((*AddLocationRequest)(nil), "proto.AddLocationRequest")
	proto1.RegisterType((*AddLocationResponse)(nil), "proto.AddLocationResponse")
	proto1.RegisterType((*GetOrganisationRequest)(nil), "proto.GetOrganisationRequest")
	proto1.RegisterType((*GetOrganisationResponse)(nil), "proto.GetOrganisationResponse")
	proto1.RegisterType((*LocateRequest)(nil), "proto.LocateRequest")
	proto1.RegisterType((*LocateResponse)(nil), "proto.LocateResponse")
	proto1.RegisterType((*QuotaRequest)(nil), "proto.QuotaRequest")
	proto1.RegisterType((*QuotaResponse)(nil), "proto.QuotaResponse")
	proto1.RegisterType((*UpdateLocationRequest)(nil), "proto.UpdateLocationRequest")
	proto1.RegisterType((*UpdateLocationResponse)(nil), "proto.UpdateLocationResponse")
	proto1.RegisterType((*AddExtractorRequest)(nil), "proto.AddExtractorRequest")
	proto1.RegisterType((*AddExtractorResponse)(nil), "proto.AddExtractorResponse")
	proto1.RegisterEnum("proto.Location_Sorting", Location_Sorting_name, Location_Sorting_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for OrganiserService service

type OrganiserServiceClient interface {
	AddLocation(ctx context.Context, in *AddLocationRequest, opts ...grpc.CallOption) (*AddLocationResponse, error)
	GetOrganisation(ctx context.Context, in *GetOrganisationRequest, opts ...grpc.CallOption) (*GetOrganisationResponse, error)
	UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error)
	Locate(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error)
	GetQuota(ctx context.Context, in *QuotaRequest, opts ...grpc.CallOption) (*QuotaResponse, error)
	AddExtractor(ctx context.Context, in *AddExtractorRequest, opts ...grpc.CallOption) (*AddExtractorResponse, error)
}

type organiserServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrganiserServiceClient(cc *grpc.ClientConn) OrganiserServiceClient {
	return &organiserServiceClient{cc}
}

func (c *organiserServiceClient) AddLocation(ctx context.Context, in *AddLocationRequest, opts ...grpc.CallOption) (*AddLocationResponse, error) {
	out := new(AddLocationResponse)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/AddLocation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) GetOrganisation(ctx context.Context, in *GetOrganisationRequest, opts ...grpc.CallOption) (*GetOrganisationResponse, error) {
	out := new(GetOrganisationResponse)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/GetOrganisation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error) {
	out := new(UpdateLocationResponse)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/UpdateLocation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) Locate(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error) {
	out := new(LocateResponse)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/Locate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) GetQuota(ctx context.Context, in *QuotaRequest, opts ...grpc.CallOption) (*QuotaResponse, error) {
	out := new(QuotaResponse)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/GetQuota", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organiserServiceClient) AddExtractor(ctx context.Context, in *AddExtractorRequest, opts ...grpc.CallOption) (*AddExtractorResponse, error) {
	out := new(AddExtractorResponse)
	err := grpc.Invoke(ctx, "/proto.OrganiserService/AddExtractor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrganiserService service

type OrganiserServiceServer interface {
	AddLocation(context.Context, *AddLocationRequest) (*AddLocationResponse, error)
	GetOrganisation(context.Context, *GetOrganisationRequest) (*GetOrganisationResponse, error)
	UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateLocationResponse, error)
	Locate(context.Context, *LocateRequest) (*LocateResponse, error)
	GetQuota(context.Context, *QuotaRequest) (*QuotaResponse, error)
	AddExtractor(context.Context, *AddExtractorRequest) (*AddExtractorResponse, error)
}

func RegisterOrganiserServiceServer(s *grpc.Server, srv OrganiserServiceServer) {
	s.RegisterService(&_OrganiserService_serviceDesc, srv)
}

func _OrganiserService_AddLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).AddLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/AddLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).AddLocation(ctx, req.(*AddLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_GetOrganisation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganisationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).GetOrganisation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/GetOrganisation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).GetOrganisation(ctx, req.(*GetOrganisationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/UpdateLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).UpdateLocation(ctx, req.(*UpdateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_Locate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).Locate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/Locate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).Locate(ctx, req.(*LocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_GetQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).GetQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/GetQuota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).GetQuota(ctx, req.(*QuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganiserService_AddExtractor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExtractorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganiserServiceServer).AddExtractor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrganiserService/AddExtractor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganiserServiceServer).AddExtractor(ctx, req.(*AddExtractorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrganiserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OrganiserService",
	HandlerType: (*OrganiserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLocation",
			Handler:    _OrganiserService_AddLocation_Handler,
		},
		{
			MethodName: "GetOrganisation",
			Handler:    _OrganiserService_GetOrganisation_Handler,
		},
		{
			MethodName: "UpdateLocation",
			Handler:    _OrganiserService_UpdateLocation_Handler,
		},
		{
			MethodName: "Locate",
			Handler:    _OrganiserService_Locate_Handler,
		},
		{
			MethodName: "GetQuota",
			Handler:    _OrganiserService_GetQuota_Handler,
		},
		{
			MethodName: "AddExtractor",
			Handler:    _OrganiserService_AddExtractor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "organise.proto",
}

func init() { proto1.RegisterFile("organise.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 971 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xae, 0xa2, 0x38, 0xb1, 0x8f, 0x7f, 0xcb, 0xfc, 0x54, 0x75, 0x9b, 0xd5, 0xd3, 0x30, 0xd4,
	0xc5, 0xb0, 0x60, 0x48, 0xb1, 0xf5, 0x66, 0x37, 0xce, 0xec, 0x74, 0x2e, 0x8c, 0xa6, 0x63, 0x3a,
	0x0c, 0x01, 0x36, 0x08, 0x8a, 0x44, 0x27, 0x02, 0x64, 0xd2, 0x25, 0xe9, 0x36, 0x7b, 0x8d, 0xdd,
	0xec, 0x65, 0xf6, 0x32, 0x7b, 0x93, 0x81, 0x3f, 0x92, 0x25, 0xc5, 0x41, 0xb1, 0x2b, 0x9b, 0xdf,
	0xe1, 0xf9, 0x0e, 0xf9, 0xf1, 0x7c, 0x47, 0xd0, 0x61, 0xfc, 0x3a, 0xa4, 0x89, 0x20, 0xc7, 0x4b,
	0xce, 0x24, 0x43, 0x35, 0xfd, 0xe3, 0xef, 0x42, 0x6d, 0xb2, 0x58, 0xca, 0x3f, 0xfd, 0x29, 0x74,
	0x66, 0xe1, 0x15, 0x49, 0x27, 0xb7, 0x92, 0x87, 0x91, 0x64, 0x1c, 0x3d, 0x86, 0x7a, 0xaa, 0x90,
	0x20, 0x89, 0x3d, 0x67, 0xe0, 0x0c, 0x6b, 0x78, 0x57, 0xaf, 0xa7, 0x31, 0x7a, 0x0a, 0x0d, 0x92,
	0xed, 0xf3, 0xb6, 0x06, 0xce, 0xb0, 0x81, 0xd7, 0x80, 0xff, 0x07, 0xf4, 0x30, 0x49, 0x49, 0x28,
	0xc8, 0xbb, 0x34, 0x8c, 0xc8, 0x82, 0x50, 0x89, 0x9e, 0x41, 0x33, 0xa1, 0x42, 0x86, 0x34, 0x22,
	0x6b, 0x3e, 0xc8, 0xa0, 0x69, 0x8c, 0xf6, 0xa1, 0x96, 0xd0, 0x98, 0xdc, 0x6a, 0xba, 0x1a, 0x36,
	0x0b, 0x84, 0x60, 0x5b, 0xa4, 0x4c, 0x7a, 0xae, 0x06, 0xf5, 0x7f, 0xff, 0x0d, 0xd4, 0x7e, 0x59,
	0x31, 0x19, 0xa2, 0x01, 0xb4, 0xe8, 0x6a, 0x11, 0xb0, 0x79, 0xa0, 0x70, 0x91, 0x91, 0xd2, 0xd5,
	0xe2, 0x7c, 0x7e, 0xa1, 0x10, 0x55, 0x55, 0x32, 0x19, 0xa6, 0xc1, 0xa7, 0x24, 0x96, 0x37, 0x96,
	0x1a, 0x34, 0xf4, 0x9b, 0x42, 0xfc, 0x7f, 0x5d, 0xa8, 0xcf, 0x58, 0x14, 0xca, 0x84, 0x51, 0x55,
	0x8c, 0x86, 0x0b, 0xa2, 0x79, 0x1a, 0x58, 0xff, 0x57, 0xc7, 0x32, 0xe4, 0xf6, 0x58, 0x7a, 0x81,
	0x8e, 0x00, 0xe6, 0x2c, 0x8d, 0x09, 0x0f, 0x92, 0x58, 0x78, 0xee, 0xc0, 0x1d, 0xd6, 0x70, 0xc3,
	0x20, 0xd3, 0x58, 0xa0, 0x31, 0x3c, 0xe4, 0x46, 0x00, 0x11, 0xa4, 0x96, 0xdd, 0xdb, 0x1e, 0xb8,
	0xc3, 0xe6, 0xc9, 0x23, 0x23, 0xff, 0x71, 0x55, 0x20, 0xdc, 0xcb, 0x32, 0xf2, 0xe3, 0x7c, 0x03,
	0xdb, 0x82, 0x71, 0xe9, 0xd5, 0x06, 0xce, 0xb0, 0x93, 0x27, 0x66, 0xe1, 0xe3, 0x0b, 0xc6, 0x65,
	0x42, 0xaf, 0xb1, 0xde, 0xa4, 0x5e, 0x44, 0x26, 0x0b, 0x22, 0x64, 0xb8, 0x58, 0x7a, 0x3b, 0x03,
	0x67, 0xe8, 0xe2, 0x35, 0x80, 0x7c, 0xa8, 0x7d, 0x50, 0x92, 0x79, 0xbb, 0x03, 0x67, 0xd8, 0x3c,
	0x69, 0x59, 0x2e, 0x2d, 0x23, 0x36, 0x21, 0xf4, 0x1c, 0xba, 0xe4, 0x76, 0x49, 0x22, 0x49, 0xe2,
	0x60, 0xce, 0xf8, 0x22, 0x94, 0x5e, 0x5d, 0x0b, 0xd1, 0xc9, 0xe0, 0x33, 0x8d, 0xa2, 0x17, 0xd0,
	0x5b, 0xd1, 0x7c, 0xab, 0x6e, 0x09, 0xaf, 0xa1, 0x77, 0x76, 0xd7, 0xb8, 0xee, 0x25, 0xd5, 0x42,
	0x94, 0x05, 0x61, 0x4a, 0xb8, 0xf4, 0x60, 0xe0, 0x0c, 0xeb, 0x78, 0x97, 0xb2, 0x91, 0x5a, 0xa2,
	0x2f, 0xa1, 0x25, 0x96, 0x49, 0x9a, 0x06, 0x46, 0x36, 0xaf, 0xa9, 0xf5, 0x6d, 0x6a, 0xec, 0x4c,
	0x43, 0xfe, 0x04, 0x76, 0xed, 0x25, 0x11, 0x82, 0xce, 0xe9, 0x65, 0x30, 0x1b, 0x9d, 0x4e, 0x66,
	0xc1, 0x4f, 0xa3, 0xf7, 0x6f, 0xcf, 0x7b, 0x0f, 0xd0, 0x43, 0x68, 0x9f, 0x5e, 0x06, 0xe3, 0xd1,
	0xfb, 0x49, 0x30, 0x1a, 0x8f, 0x27, 0xe3, 0x9e, 0x83, 0xf6, 0xa0, 0x7b, 0x7a, 0x19, 0xe0, 0xc9,
	0x6c, 0x32, 0xba, 0x98, 0xe8, 0x50, 0x6f, 0xcb, 0xff, 0xcb, 0x81, 0xd6, 0xb9, 0x69, 0x7e, 0x23,
	0x6c, 0x49, 0x2b, 0xa7, 0xaa, 0xd5, 0xb7, 0xd0, 0xc8, 0xde, 0x4c, 0xbd, 0xba, 0x7a, 0xb4, 0x6e,
	0x45, 0x7b, 0xbc, 0xde, 0x81, 0xbe, 0x07, 0xc8, 0x3b, 0xdf, 0xb4, 0x42, 0xf3, 0xe4, 0x20, 0xdb,
	0x5f, 0x32, 0x14, 0x2e, 0x6c, 0xf4, 0x5f, 0x01, 0x1a, 0xc5, 0x71, 0x4e, 0x48, 0x3e, 0xac, 0x88,
	0x50, 0xa2, 0xb8, 0x61, 0x6c, 0xdc, 0xb1, 0xa1, 0xaa, 0x8a, 0xf9, 0x3f, 0xc2, 0x5e, 0x29, 0x51,
	0x2c, 0x19, 0x15, 0x04, 0x7d, 0x0d, 0x2e, 0x65, 0x9f, 0x6c, 0xe6, 0x9e, 0xcd, 0x2c, 0xde, 0x1a,
	0xab, 0xb8, 0x7f, 0x03, 0x87, 0xaf, 0x89, 0x2c, 0xe1, 0xb6, 0x74, 0xe9, 0xda, 0xce, 0x67, 0xaf,
	0xfd, 0x0c, 0x9a, 0x73, 0xc6, 0x23, 0x12, 0x70, 0xc2, 0xf8, 0xb5, 0x76, 0x47, 0x1d, 0x83, 0x86,
	0xb0, 0x42, 0x7c, 0x01, 0x8f, 0xee, 0x54, 0xb2, 0x67, 0xfd, 0x9f, 0xa5, 0x5e, 0x40, 0x8f, 0xae,
	0x16, 0x57, 0x84, 0x07, 0x4b, 0xce, 0x22, 0x22, 0x04, 0x89, 0xad, 0x1b, 0xbb, 0x06, 0x7f, 0x97,
	0xc1, 0xfe, 0x77, 0xd0, 0xd6, 0x0c, 0x24, 0xbb, 0xd5, 0xe7, 0xc6, 0x8e, 0xff, 0x33, 0x74, 0xb2,
	0x0c, 0x7b, 0xba, 0x1f, 0xa0, 0x33, 0x67, 0x2b, 0x1a, 0xaf, 0x9d, 0xbb, 0xb5, 0xf9, 0x39, 0xda,
	0x7a, 0x5b, 0xb6, 0xf4, 0x6f, 0xa0, 0x65, 0xfc, 0x64, 0x4b, 0x3f, 0x81, 0x46, 0x3e, 0x23, 0x6c,
	0xe1, 0x7a, 0x36, 0x22, 0x94, 0xd9, 0x12, 0x1a, 0xa5, 0xab, 0x58, 0x09, 0x18, 0x31, 0x1e, 0x0b,
	0x2b, 0x61, 0xc7, 0xc2, 0xd8, 0xa0, 0xf9, 0x4c, 0x72, 0xd7, 0x33, 0xc9, 0xff, 0xdb, 0x81, 0xb6,
	0x2d, 0x65, 0xcf, 0x7c, 0x04, 0xc0, 0x3e, 0x12, 0x1e, 0x18, 0x93, 0x3b, 0x9a, 0xa9, 0xa1, 0x10,
	0x33, 0x28, 0xab, 0x5e, 0xdb, 0xba, 0xe3, 0x35, 0xf4, 0x15, 0xb4, 0xb3, 0xfb, 0x06, 0x85, 0x82,
	0xad, 0x0c, 0x7c, 0xab, 0x86, 0x61, 0x45, 0xcd, 0x6d, 0x3d, 0xf7, 0x8a, 0x6a, 0xfe, 0x0e, 0x07,
	0xbf, 0x2e, 0xe3, 0x50, 0x92, 0x6a, 0x63, 0xf7, 0xa1, 0x9e, 0xcb, 0x69, 0xc6, 0x6b, 0xbe, 0x46,
	0xcf, 0x61, 0x67, 0xa5, 0x93, 0xee, 0x13, 0xda, 0x86, 0x7d, 0x0f, 0x0e, 0xab, 0xec, 0xe6, 0xfe,
	0xfe, 0x1b, 0x6d, 0x8a, 0xb5, 0xd3, 0x6c, 0xd5, 0x97, 0xc5, 0xcf, 0x94, 0xb1, 0xc6, 0x3d, 0xd6,
	0x2c, 0x7c, 0xbd, 0x0e, 0x61, 0xbf, 0xcc, 0x65, 0x6a, 0x9c, 0xfc, 0xe3, 0x42, 0xcf, 0xb6, 0x33,
	0xe1, 0x17, 0x84, 0x7f, 0x4c, 0x22, 0x82, 0xce, 0xa0, 0x59, 0x70, 0x23, 0x7a, 0x6c, 0xd9, 0xef,
	0x5a, 0xbb, 0xdf, 0xdf, 0x14, 0xb2, 0xc7, 0x7f, 0x80, 0x30, 0x74, 0x2b, 0x6e, 0x41, 0x47, 0x36,
	0x61, 0xb3, 0x5f, 0xfb, 0x5f, 0xdc, 0x17, 0xce, 0x39, 0xcf, 0xa1, 0x53, 0x96, 0x0b, 0x3d, 0xb5,
	0x39, 0x1b, 0xdf, 0xa8, 0x7f, 0x74, 0x4f, 0x34, 0x27, 0x7c, 0x05, 0x3b, 0xc6, 0x2b, 0x68, 0xbf,
	0xf8, 0x44, 0x99, 0xd9, 0xfa, 0x07, 0x15, 0xb4, 0x90, 0x58, 0x7f, 0x4d, 0xa4, 0xe9, 0xc5, 0xbd,
	0xd2, 0xb7, 0xc7, 0x66, 0xee, 0x97, 0xc1, 0x3c, 0x71, 0x0a, 0xad, 0xe2, 0x5b, 0xa0, 0x82, 0x88,
	0xd5, 0xc7, 0xee, 0x3f, 0xd9, 0x18, 0xcb, 0xa8, 0xae, 0x76, 0x74, 0xf4, 0xe5, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xf8, 0x7b, 0x1b, 0xd6, 0x08, 0x09, 0x00, 0x00,
}
